Other user/russian lang money
vj12354/amonies-lang pull request #13
Opened 2020-08-21 10:29 UTC by shanth5100

Sir we are splitting it into two branches, remain changes will be in another branch

2020-08-23 20:00 UTC, vj12354 reviewed
You also need to work on **cats strings.xml** file, which is used by Bill Reminder features of the App.
`androidapp/cats/src/main/res/values-ru/strings.xml`

2020-08-23 20:00 UTC, vj12354 commented on androidapp/money/src/main/res/values-ru/strings.xml
> +    <string name="menu_bills_header">НАПОМИНАНИЕ О СЧЕТАХ</string>
Why all are upper case? Is this not first Capital in the default language?

2020-08-23 20:00 UTC, vj12354 commented on androidapp/money/src/main/res/values-ru/strings.xml
> +    <string name="acct_desc_default">Начальный баланс счета составляет: %1$s</string>
better to use something like:
_Account opening balance is %1$s_

> Example: **Account opening balance is 20,000**
> OR: **Account opening balance is 104.89**
> So it will look differently for languages like Hindi, etc.

2020-08-23 20:00 UTC, vj12354 commented on androidapp/money/src/main/res/values-ru/strings.xml
> +    <string name="tx_bill_pmt_not_selected">Пожалуйста, выберите законопроект, чтобы завершить оплату счета.</string>
I think the correct translation is: **Выберите счет, чтобы завершить его оплату.**

2020-08-23 20:01 UTC, vj12354 requested changes
Please address the comments made and let me know for an re-review.

2020-08-24 14:51 UTC, shanth5100 commented on androidapp/money/src/main/res/values-ru/strings.xml
> +    <string name="menu_bills_header">НАПОМИНАНИЕ О СЧЕТАХ</string>
Sir corrected

2020-08-24 14:51 UTC, shanth5100 commented
> You also need to work on **cats strings.xml** file, which is used by Bill Reminder features of the App.
> `androidapp/cats/src/main/res/values-ru/strings.xml`

2020-08-24 14:51 UTC, closed without merging